project_id = "pppacjvewskrmliieyty"

[functions.financial-insights]
verify_jwt = false

[functions.parse-csv]
verify_jwt = false

[functions.auto-map-categories]
verify_jwt = false

[functions.auto-fill-entries]
verify_jwt = false

[functions.detect-anomalies]
verify_jwt = false
