#!/bin/bash
# ══════════════════════════════════════════════════════════════
# Weekly Skill Ecosystem Analysis
# Runs a full audit of the skills ecosystem and checks for updates
# ══════════════════════════════════════════════════════════════
#
# Usage:
#   bash scripts/weekly-skill-analysis.sh
#   # or via cron:
#   0 9 * * 1 cd /path/to/ai-agent12 && bash scripts/weekly-skill-analysis.sh >> logs/weekly-analysis.log 2>&1
#
# What it does:
#   1. Audits current skill/agent/command inventory
#   2. Checks source repos for new content via GitHub API
#   3. Identifies gaps, stale skills, and opportunities
#   4. Generates a report in reports/weekly-analysis-<date>.md

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$PROJECT_DIR/reports"
DATE=$(date +%Y-%m-%d)
REPORT_FILE="$REPORT_DIR/weekly-analysis-$DATE.md"

mkdir -p "$REPORT_DIR"

echo "Running weekly skill ecosystem analysis..."
echo ""

# ── 1. Current Inventory ──
SKILLS=$(find "$PROJECT_DIR/.claude/skills" -name "*.md" | wc -l | tr -d ' ')
AGENTS=$(find "$PROJECT_DIR/.claude/agents" -name "*.md" | wc -l | tr -d ' ')
COMMANDS=$(find "$PROJECT_DIR/.claude/commands" -name "*.md" | wc -l | tr -d ' ')
TOTAL=$((SKILLS + AGENTS + COMMANDS))

# ── 2. Category breakdown ──
CATEGORIES=""
for f in "$PROJECT_DIR/.claude/skills/"*.md; do
  basename "$f" .md
done | sort > /tmp/current-skills.txt

# ── 3. Check for stale skills (not modified in 90+ days) ──
STALE_COUNT=0
STALE_LIST=""
for f in "$PROJECT_DIR/.claude/skills/"*.md; do
  if [ "$(uname -s)" = "Darwin" ]; then
    MOD_DATE=$(stat -f %m "$f")
    NINETY_AGO=$(date -v-90d +%s)
  else
    MOD_DATE=$(stat -c %Y "$f")
    NINETY_AGO=$(date -d '90 days ago' +%s)
  fi
  if [ "$MOD_DATE" -lt "$NINETY_AGO" ]; then
    STALE_COUNT=$((STALE_COUNT + 1))
    STALE_LIST="$STALE_LIST\n- $(basename "$f" .md)"
  fi
done

# ── 4. Check source repos for updates ──
ANTHROPIC_NEW=0
ECC_NEW=0
AWESOME_NEW=0

# Check anthropics/skills via GitHub API
if command -v gh &> /dev/null; then
  ANTHROPIC_SKILLS=$(gh api repos/anthropics/skills/contents/skills 2>/dev/null | grep -c '"name"' || echo "0")
  ANTHROPIC_NEW=$((ANTHROPIC_SKILLS > 0 ? ANTHROPIC_SKILLS - SKILLS : 0))
  ANTHROPIC_NEW=$((ANTHROPIC_NEW < 0 ? 0 : ANTHROPIC_NEW))

  # Check ECC for new skills directories
  ECC_SKILLS=$(gh api repos/affaan-m/everything-claude-code/contents/.claude/skills 2>/dev/null | grep -c '"name"' || echo "0")

  # Check awesome-claude-skills
  AWESOME_TOTAL=$(gh api repos/karanb192/awesome-claude-skills 2>/dev/null | grep -o '"size":[0-9]*' | head -1 || echo "0")
else
  echo "Note: 'gh' CLI not found. Skipping remote repo checks."
  echo "Install with: brew install gh (Mac) or apt install gh (Linux)"
fi

# ── 5. Quality audit ──
MISSING_INSTRUCTIONS=0
SHORT_FILES=0
for f in "$PROJECT_DIR/.claude/skills/"*.md; do
  if ! grep -q "## Instructions" "$f" 2>/dev/null; then
    MISSING_INSTRUCTIONS=$((MISSING_INSTRUCTIONS + 1))
  fi
  LINES=$(wc -l < "$f" | tr -d ' ')
  if [ "$LINES" -lt 4 ]; then
    SHORT_FILES=$((SHORT_FILES + 1))
  fi
done

# ── 6. Generate Report ──
cat > "$REPORT_FILE" << EOF
# Weekly Skill Ecosystem Analysis — $DATE

## Current Inventory

| Type | Count |
|------|-------|
| Skills | $SKILLS |
| Agents | $AGENTS |
| Commands | $COMMANDS |
| **Total** | **$TOTAL** |

## Quality Audit

| Check | Result |
|-------|--------|
| Skills missing \`## Instructions\` | $MISSING_INSTRUCTIONS |
| Files too short (< 4 lines) | $SHORT_FILES |
| Stale skills (90+ days unmodified) | $STALE_COUNT |

## Source Repository Status

| Source | Status |
|--------|--------|
| anthropics/skills | Checked |
| affaan-m/everything-claude-code | Checked |
| karanb192/awesome-claude-skills | Checked |

## Recommendations

$(if [ "$MISSING_INSTRUCTIONS" -gt 0 ]; then echo "- Fix $MISSING_INSTRUCTIONS skills missing \`## Instructions\` section"; fi)
$(if [ "$SHORT_FILES" -gt 0 ]; then echo "- Expand $SHORT_FILES skills that are too short (< 4 lines)"; fi)
$(if [ "$STALE_COUNT" -gt 0 ]; then echo "- Review $STALE_COUNT stale skills for relevance"; fi)
- Run \`/auto-update --scan-only\` in Claude Code for deeper analysis
- Check GitHub trending for new claude-code repos

## Next Steps

1. Run \`/auto-update\` in a Claude Code session to discover and integrate new skills
2. Review any HIGH-scored candidates and approve integration
3. Run \`bash scripts/install-claude-skills-global.sh\` to sync updates globally

---
*Generated by weekly-skill-analysis.sh*
EOF

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Weekly Analysis Complete                                ║"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║  Skills:   $SKILLS                                       "
echo "║  Agents:   $AGENTS                                       "
echo "║  Commands: $COMMANDS                                     "
echo "║  Total:    $TOTAL                                        "
echo "╠══════════════════════════════════════════════════════════╣"
echo "║  Quality Issues: $MISSING_INSTRUCTIONS missing instructions, $SHORT_FILES too short"
echo "║  Stale Skills:   $STALE_COUNT (90+ days unmodified)      "
echo "╠══════════════════════════════════════════════════════════╣"
echo "║  Report: $REPORT_FILE"
echo "╚══════════════════════════════════════════════════════════╝"
